---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html

- name: "add user {{ user.ansible.login }}"
  ansible.builtin.user:
    state: present
    name: "{{ user.ansible.login }}"
    group: "{{ user.ansible.login }}"
    groups: "{{ user.ansible.groups }}"
    shell: "{{ user.ansible.shell }}"
    home: "{{ user.ansible.home }}"
    password: "{{ user.ansible.hash }}"
    uid: "{{ user.ansible.uid }}"
